#!/usr/bin/env bash
# Janus — server installer.
#
# Sets up the NSE stack as systemd services and (optionally) brings up the
# Forex stack via Docker Compose. Idempotent — re-running is safe.
#
# Usage:
#   sudo ./install.sh              # NSE only (systemd)
#   sudo ./install.sh --with-forex # NSE (systemd) + Forex (Docker)
#   sudo ./install.sh --forex-only # Forex (Docker) only
#
# Run from a checkout that has submodules initialised:
#   git clone --recurse-submodules https://github.com/sppidy/janus.git
#   cd janus && sudo ./install.sh

set -euo pipefail

# ── Defaults (override via env) ───────────────────────────────────────────
JANUS_USER="${JANUS_USER:-ubuntu}"
JANUS_ROOT="${JANUS_ROOT:-/home/$JANUS_USER/janus}"
JANUS_ENV_DIR="${JANUS_ENV_DIR:-/etc/janus}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

WITH_FOREX=0
FOREX_ONLY=0
for arg in "$@"; do
    case "$arg" in
        --with-forex) WITH_FOREX=1 ;;
        --forex-only) FOREX_ONLY=1 ;;
        -h|--help)
            sed -n '2,12p' "$0"
            exit 0
            ;;
        *) echo "Unknown arg: $arg" >&2; exit 2 ;;
    esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

require_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "✗ This script needs root (writes systemd units + /etc/janus)." >&2
        echo "  Re-run with: sudo $0 $*" >&2
        exit 1
    fi
}

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || { echo "✗ Missing command: $1" >&2; exit 1; }
}

# ─────────────────────────────────────────────────────────────────────────
# NSE stack — systemd
# ─────────────────────────────────────────────────────────────────────────
install_nse_systemd() {
    echo "=== Janus NSE → systemd ==="
    require_root
    require_cmd "$PYTHON_BIN"
    require_cmd systemctl

    # Sanity: submodules present
    for sub in nse-agent nse-backend; do
        if [[ ! -d "$REPO_ROOT/$sub" ]] || [[ -z "$(ls -A "$REPO_ROOT/$sub" 2>/dev/null)" ]]; then
            echo "✗ $sub/ submodule is missing or empty. Run: git submodule update --init $sub" >&2
            exit 1
        fi
    done

    # Place repo at $JANUS_ROOT (skip if already there)
    if [[ "$REPO_ROOT" != "$JANUS_ROOT" ]]; then
        echo "  Linking repo to $JANUS_ROOT (current location: $REPO_ROOT)"
        mkdir -p "$(dirname "$JANUS_ROOT")"
        if [[ -e "$JANUS_ROOT" ]] && [[ ! -L "$JANUS_ROOT" ]]; then
            echo "    NOTE: $JANUS_ROOT exists and is not a symlink — leaving it alone."
        elif [[ ! -e "$JANUS_ROOT" ]]; then
            ln -s "$REPO_ROOT" "$JANUS_ROOT"
        fi
    fi

    # Per-component venvs
    for sub in nse-agent nse-backend; do
        venv="$JANUS_ROOT/$sub/venv"
        if [[ ! -d "$venv" ]]; then
            echo "  Creating venv: $venv"
            sudo -u "$JANUS_USER" "$PYTHON_BIN" -m venv "$venv"
        fi
        echo "  Installing $sub deps…"
        sudo -u "$JANUS_USER" "$venv/bin/pip" install --quiet --upgrade pip
        sudo -u "$JANUS_USER" "$venv/bin/pip" install --quiet -r "$JANUS_ROOT/$sub/requirements.txt"
    done

    # logs dir
    sudo -u "$JANUS_USER" mkdir -p "$JANUS_ROOT/nse-agent/logs"

    # /etc/janus/nse.env (idempotent — only seeds, never overwrites)
    mkdir -p "$JANUS_ENV_DIR"
    chmod 750 "$JANUS_ENV_DIR"
    if [[ ! -f "$JANUS_ENV_DIR/nse.env" ]]; then
        echo "  Seeding $JANUS_ENV_DIR/nse.env (you must fill API_AUTH_TOKEN before starting)…"
        cat > "$JANUS_ENV_DIR/nse.env" <<EOF
# Generated by install.sh — fill in real values, then \`systemctl restart janus-nse-api janus-nse-agent\`.
# REQUIRED:
API_AUTH_TOKEN=

# Comma-separated allowed CORS origins.
TRUSTED_ORIGINS=http://localhost:8443

# Optional — leave blank to use yfinance instead of Groww.
GROWW_API_KEY=
GROWW_TOTP_SECRET=
GROWW_ACCESS_TOKEN=

# At least one LLM key is required.
GROQ_API_KEY=
GEMINI_API_KEY=
OPENROUTER_API_KEY=
CLOUDFLARE_API_TOKEN=
CLOUDFLARE_ACCOUNT_ID=
OLLAMA_BASE_URL=

# Tamper-resistant pickle loading. Generate: python -c "import secrets; print(secrets.token_hex(32))"
MODEL_HMAC_SECRET=
EOF
        chmod 600 "$JANUS_ENV_DIR/nse.env"
        chown root:"$JANUS_USER" "$JANUS_ENV_DIR/nse.env"
    else
        echo "  $JANUS_ENV_DIR/nse.env exists — leaving alone."
    fi

    # Install unit files
    install -m 0644 "$REPO_ROOT/nse-backend/janus-nse-api.service"  /etc/systemd/system/janus-nse-api.service
    install -m 0644 "$REPO_ROOT/nse-agent/janus-nse-agent.service" /etc/systemd/system/janus-nse-agent.service

    systemctl daemon-reload
    systemctl enable janus-nse-api.service janus-nse-agent.service

    echo ""
    echo "=== Janus NSE installed ==="
    echo "  Edit:  sudoedit $JANUS_ENV_DIR/nse.env"
    echo "  Start: sudo systemctl start janus-nse-api janus-nse-agent"
    echo "  Logs:  sudo journalctl -u janus-nse-api -f"
    echo ""
}

# ─────────────────────────────────────────────────────────────────────────
# Forex stack — Docker
# ─────────────────────────────────────────────────────────────────────────
install_forex_docker() {
    echo "=== Janus Forex → Docker Compose ==="
    require_cmd docker
    if ! docker compose version >/dev/null 2>&1; then
        echo "✗ 'docker compose' (v2) plugin not available." >&2
        exit 1
    fi

    if [[ ! -f "$REPO_ROOT/.env.docker" ]]; then
        if [[ ! -f "$REPO_ROOT/.env.docker.example" ]]; then
            echo "✗ .env.docker.example missing — bad checkout?" >&2
            exit 1
        fi
        cp "$REPO_ROOT/.env.docker.example" "$REPO_ROOT/.env.docker"
        chmod 600 "$REPO_ROOT/.env.docker"
        echo "  Seeded $REPO_ROOT/.env.docker — fill it in then re-run, OR docker compose up directly."
        return
    fi

    cd "$REPO_ROOT"
    echo "  Building images…"
    docker compose --env-file .env.docker -f docker-compose.yml build forex-postgres forex-api forex-autopilot
    echo "  Starting…"
    docker compose --env-file .env.docker -f docker-compose.yml up -d forex-postgres forex-api forex-autopilot
    echo ""
    echo "=== Janus Forex up ==="
    echo "  Status:    docker compose ps"
    echo "  Logs:      docker compose logs -f forex-api forex-autopilot"
    echo "  Admin key: docker compose exec forex-api cat /run/forex/admin.key"
    echo ""
}

# ─────────────────────────────────────────────────────────────────────────
# Drive
# ─────────────────────────────────────────────────────────────────────────
if [[ $FOREX_ONLY -eq 1 ]]; then
    install_forex_docker
else
    install_nse_systemd
    if [[ $WITH_FOREX -eq 1 ]]; then
        install_forex_docker
    fi
fi

echo "All done."
